CREATE DATABASE Moviepass;

USE Moviepass;

CREATE TABLE cinemas
(
	id INT AUTO_INCREMENT NOT NULL ,
    state BOOLEAN NOT NULL,
    address VARCHAR(100) NOT NULL,
    phone INT NOT NULL,
    email NVARCHAR(100) NOt NULL,
    CONSTRAINT `PK_cinema` PRIMARY KEY (id)

)ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;

